// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreBurrow.Data;

#nullable disable

namespace ScoreBurrow.Data.Migrations
{
    [DbContext(typeof(ScoreBurrowDbContext))]
    [Migration("20251104073916_AddMissingHeroes")]
    partial class AddMissingHeroes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.GameParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GoldTrade")
                        .HasColumnType("int");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTechnicalLoss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeagueMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerColor")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("RatingAtGameTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatingDeviationAtGameTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.Property<decimal>("VolatilityAtGameTime")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("HeroId");

                    b.HasIndex("LeagueMembershipId");

                    b.HasIndex("TownId");

                    b.HasIndex("GameId", "PlayerColor")
                        .IsUnique();

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeroClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeroClass = "Knight",
                            Name = "Orrin",
                            TownId = 1
                        },
                        new
                        {
                            Id = 2,
                            HeroClass = "Knight",
                            Name = "Valeska",
                            TownId = 1
                        },
                        new
                        {
                            Id = 3,
                            HeroClass = "Knight",
                            Name = "Edric",
                            TownId = 1
                        },
                        new
                        {
                            Id = 4,
                            HeroClass = "Knight",
                            Name = "Sylvia",
                            TownId = 1
                        },
                        new
                        {
                            Id = 5,
                            HeroClass = "Knight",
                            Name = "Lord Haart",
                            TownId = 1
                        },
                        new
                        {
                            Id = 6,
                            HeroClass = "Knight",
                            Name = "Sorsha",
                            TownId = 1
                        },
                        new
                        {
                            Id = 7,
                            HeroClass = "Knight",
                            Name = "Christian",
                            TownId = 1
                        },
                        new
                        {
                            Id = 8,
                            HeroClass = "Knight",
                            Name = "Tyris",
                            TownId = 1
                        },
                        new
                        {
                            Id = 9,
                            HeroClass = "Cleric",
                            Name = "Rion",
                            TownId = 1
                        },
                        new
                        {
                            Id = 10,
                            HeroClass = "Cleric",
                            Name = "Adela",
                            TownId = 1
                        },
                        new
                        {
                            Id = 11,
                            HeroClass = "Cleric",
                            Name = "Cuthbert",
                            TownId = 1
                        },
                        new
                        {
                            Id = 12,
                            HeroClass = "Cleric",
                            Name = "Adelaide",
                            TownId = 1
                        },
                        new
                        {
                            Id = 13,
                            HeroClass = "Cleric",
                            Name = "Ingham",
                            TownId = 1
                        },
                        new
                        {
                            Id = 14,
                            HeroClass = "Cleric",
                            Name = "Sanya",
                            TownId = 1
                        },
                        new
                        {
                            Id = 15,
                            HeroClass = "Cleric",
                            Name = "Loynis",
                            TownId = 1
                        },
                        new
                        {
                            Id = 16,
                            HeroClass = "Cleric",
                            Name = "Caitlin",
                            TownId = 1
                        },
                        new
                        {
                            Id = 17,
                            HeroClass = "Ranger",
                            Name = "Mephala",
                            TownId = 2
                        },
                        new
                        {
                            Id = 18,
                            HeroClass = "Ranger",
                            Name = "Ufretin",
                            TownId = 2
                        },
                        new
                        {
                            Id = 19,
                            HeroClass = "Ranger",
                            Name = "Jenova",
                            TownId = 2
                        },
                        new
                        {
                            Id = 20,
                            HeroClass = "Ranger",
                            Name = "Ryland",
                            TownId = 2
                        },
                        new
                        {
                            Id = 21,
                            HeroClass = "Ranger",
                            Name = "Thorgrim",
                            TownId = 2
                        },
                        new
                        {
                            Id = 22,
                            HeroClass = "Ranger",
                            Name = "Ivor",
                            TownId = 2
                        },
                        new
                        {
                            Id = 23,
                            HeroClass = "Ranger",
                            Name = "Clancy",
                            TownId = 2
                        },
                        new
                        {
                            Id = 24,
                            HeroClass = "Ranger",
                            Name = "Kyrre",
                            TownId = 2
                        },
                        new
                        {
                            Id = 25,
                            HeroClass = "Druid",
                            Name = "Coronius",
                            TownId = 2
                        },
                        new
                        {
                            Id = 26,
                            HeroClass = "Druid",
                            Name = "Uland",
                            TownId = 2
                        },
                        new
                        {
                            Id = 27,
                            HeroClass = "Druid",
                            Name = "Elleshar",
                            TownId = 2
                        },
                        new
                        {
                            Id = 28,
                            HeroClass = "Druid",
                            Name = "Gem",
                            TownId = 2
                        },
                        new
                        {
                            Id = 29,
                            HeroClass = "Druid",
                            Name = "Malcom",
                            TownId = 2
                        },
                        new
                        {
                            Id = 30,
                            HeroClass = "Druid",
                            Name = "Melodia",
                            TownId = 2
                        },
                        new
                        {
                            Id = 31,
                            HeroClass = "Druid",
                            Name = "Alagar",
                            TownId = 2
                        },
                        new
                        {
                            Id = 32,
                            HeroClass = "Druid",
                            Name = "Aeris",
                            TownId = 2
                        },
                        new
                        {
                            Id = 33,
                            HeroClass = "Alchemist",
                            Name = "Piquedram",
                            TownId = 3
                        },
                        new
                        {
                            Id = 34,
                            HeroClass = "Alchemist",
                            Name = "Thane",
                            TownId = 3
                        },
                        new
                        {
                            Id = 35,
                            HeroClass = "Alchemist",
                            Name = "Josephine",
                            TownId = 3
                        },
                        new
                        {
                            Id = 36,
                            HeroClass = "Alchemist",
                            Name = "Neela",
                            TownId = 3
                        },
                        new
                        {
                            Id = 37,
                            HeroClass = "Alchemist",
                            Name = "Torosar",
                            TownId = 3
                        },
                        new
                        {
                            Id = 38,
                            HeroClass = "Alchemist",
                            Name = "Fafner",
                            TownId = 3
                        },
                        new
                        {
                            Id = 39,
                            HeroClass = "Alchemist",
                            Name = "Rissa",
                            TownId = 3
                        },
                        new
                        {
                            Id = 40,
                            HeroClass = "Alchemist",
                            Name = "Iona",
                            TownId = 3
                        },
                        new
                        {
                            Id = 41,
                            HeroClass = "Wizard",
                            Name = "Astral",
                            TownId = 3
                        },
                        new
                        {
                            Id = 42,
                            HeroClass = "Wizard",
                            Name = "Halon",
                            TownId = 3
                        },
                        new
                        {
                            Id = 43,
                            HeroClass = "Wizard",
                            Name = "Serena",
                            TownId = 3
                        },
                        new
                        {
                            Id = 44,
                            HeroClass = "Wizard",
                            Name = "Daremyth",
                            TownId = 3
                        },
                        new
                        {
                            Id = 45,
                            HeroClass = "Wizard",
                            Name = "Theodorus",
                            TownId = 3
                        },
                        new
                        {
                            Id = 46,
                            HeroClass = "Wizard",
                            Name = "Solmyr",
                            TownId = 3
                        },
                        new
                        {
                            Id = 47,
                            HeroClass = "Wizard",
                            Name = "Cyra",
                            TownId = 3
                        },
                        new
                        {
                            Id = 48,
                            HeroClass = "Wizard",
                            Name = "Aine",
                            TownId = 3
                        },
                        new
                        {
                            Id = 49,
                            HeroClass = "Demoniac",
                            Name = "Fiona",
                            TownId = 4
                        },
                        new
                        {
                            Id = 50,
                            HeroClass = "Demoniac",
                            Name = "Rashka",
                            TownId = 4
                        },
                        new
                        {
                            Id = 51,
                            HeroClass = "Demoniac",
                            Name = "Marius",
                            TownId = 4
                        },
                        new
                        {
                            Id = 52,
                            HeroClass = "Demoniac",
                            Name = "Ignatius",
                            TownId = 4
                        },
                        new
                        {
                            Id = 53,
                            HeroClass = "Demoniac",
                            Name = "Octavia",
                            TownId = 4
                        },
                        new
                        {
                            Id = 54,
                            HeroClass = "Demoniac",
                            Name = "Calh",
                            TownId = 4
                        },
                        new
                        {
                            Id = 55,
                            HeroClass = "Demoniac",
                            Name = "Pyre",
                            TownId = 4
                        },
                        new
                        {
                            Id = 56,
                            HeroClass = "Demoniac",
                            Name = "Nymus",
                            TownId = 4
                        },
                        new
                        {
                            Id = 57,
                            HeroClass = "Heretic",
                            Name = "Ayden",
                            TownId = 4
                        },
                        new
                        {
                            Id = 58,
                            HeroClass = "Heretic",
                            Name = "Xyron",
                            TownId = 4
                        },
                        new
                        {
                            Id = 59,
                            HeroClass = "Heretic",
                            Name = "Axsis",
                            TownId = 4
                        },
                        new
                        {
                            Id = 60,
                            HeroClass = "Heretic",
                            Name = "Olema",
                            TownId = 4
                        },
                        new
                        {
                            Id = 61,
                            HeroClass = "Heretic",
                            Name = "Calid",
                            TownId = 4
                        },
                        new
                        {
                            Id = 62,
                            HeroClass = "Heretic",
                            Name = "Ash",
                            TownId = 4
                        },
                        new
                        {
                            Id = 63,
                            HeroClass = "Heretic",
                            Name = "Zydar",
                            TownId = 4
                        },
                        new
                        {
                            Id = 64,
                            HeroClass = "Heretic",
                            Name = "Xarfax",
                            TownId = 4
                        },
                        new
                        {
                            Id = 65,
                            HeroClass = "Death Knight",
                            Name = "Straker",
                            TownId = 5
                        },
                        new
                        {
                            Id = 66,
                            HeroClass = "Death Knight",
                            Name = "Vokial",
                            TownId = 5
                        },
                        new
                        {
                            Id = 67,
                            HeroClass = "Death Knight",
                            Name = "Moandor",
                            TownId = 5
                        },
                        new
                        {
                            Id = 68,
                            HeroClass = "Death Knight",
                            Name = "Charna",
                            TownId = 5
                        },
                        new
                        {
                            Id = 69,
                            HeroClass = "Death Knight",
                            Name = "Tamika",
                            TownId = 5
                        },
                        new
                        {
                            Id = 70,
                            HeroClass = "Death Knight",
                            Name = "Isra",
                            TownId = 5
                        },
                        new
                        {
                            Id = 71,
                            HeroClass = "Death Knight",
                            Name = "Clavius",
                            TownId = 5
                        },
                        new
                        {
                            Id = 72,
                            HeroClass = "Death Knight",
                            Name = "Galthran",
                            TownId = 5
                        },
                        new
                        {
                            Id = 73,
                            HeroClass = "Necromancer",
                            Name = "Septienna",
                            TownId = 5
                        },
                        new
                        {
                            Id = 74,
                            HeroClass = "Necromancer",
                            Name = "Aislinn",
                            TownId = 5
                        },
                        new
                        {
                            Id = 75,
                            HeroClass = "Necromancer",
                            Name = "Sandro",
                            TownId = 5
                        },
                        new
                        {
                            Id = 76,
                            HeroClass = "Necromancer",
                            Name = "Nimbus",
                            TownId = 5
                        },
                        new
                        {
                            Id = 77,
                            HeroClass = "Necromancer",
                            Name = "Thant",
                            TownId = 5
                        },
                        new
                        {
                            Id = 78,
                            HeroClass = "Necromancer",
                            Name = "Xsi",
                            TownId = 5
                        },
                        new
                        {
                            Id = 79,
                            HeroClass = "Necromancer",
                            Name = "Vidomina",
                            TownId = 5
                        },
                        new
                        {
                            Id = 80,
                            HeroClass = "Necromancer",
                            Name = "Nagash",
                            TownId = 5
                        },
                        new
                        {
                            Id = 81,
                            HeroClass = "Overlord",
                            Name = "Lorelei",
                            TownId = 6
                        },
                        new
                        {
                            Id = 82,
                            HeroClass = "Overlord",
                            Name = "Arlach",
                            TownId = 6
                        },
                        new
                        {
                            Id = 83,
                            HeroClass = "Overlord",
                            Name = "Dace",
                            TownId = 6
                        },
                        new
                        {
                            Id = 84,
                            HeroClass = "Overlord",
                            Name = "Ajit",
                            TownId = 6
                        },
                        new
                        {
                            Id = 85,
                            HeroClass = "Overlord",
                            Name = "Damacon",
                            TownId = 6
                        },
                        new
                        {
                            Id = 86,
                            HeroClass = "Overlord",
                            Name = "Gunnar",
                            TownId = 6
                        },
                        new
                        {
                            Id = 87,
                            HeroClass = "Overlord",
                            Name = "Synca",
                            TownId = 6
                        },
                        new
                        {
                            Id = 88,
                            HeroClass = "Overlord",
                            Name = "Shakti",
                            TownId = 6
                        },
                        new
                        {
                            Id = 89,
                            HeroClass = "Warlock",
                            Name = "Alamar",
                            TownId = 6
                        },
                        new
                        {
                            Id = 90,
                            HeroClass = "Warlock",
                            Name = "Jaegar",
                            TownId = 6
                        },
                        new
                        {
                            Id = 91,
                            HeroClass = "Warlock",
                            Name = "Malekith",
                            TownId = 6
                        },
                        new
                        {
                            Id = 92,
                            HeroClass = "Warlock",
                            Name = "Jeddite",
                            TownId = 6
                        },
                        new
                        {
                            Id = 93,
                            HeroClass = "Warlock",
                            Name = "Geon",
                            TownId = 6
                        },
                        new
                        {
                            Id = 94,
                            HeroClass = "Warlock",
                            Name = "Deemer",
                            TownId = 6
                        },
                        new
                        {
                            Id = 95,
                            HeroClass = "Warlock",
                            Name = "Sephinroth",
                            TownId = 6
                        },
                        new
                        {
                            Id = 96,
                            HeroClass = "Warlock",
                            Name = "Darkstorn",
                            TownId = 6
                        },
                        new
                        {
                            Id = 97,
                            HeroClass = "Barbarian",
                            Name = "Yog",
                            TownId = 7
                        },
                        new
                        {
                            Id = 98,
                            HeroClass = "Barbarian",
                            Name = "Gurnisson",
                            TownId = 7
                        },
                        new
                        {
                            Id = 99,
                            HeroClass = "Barbarian",
                            Name = "Jabarkas",
                            TownId = 7
                        },
                        new
                        {
                            Id = 100,
                            HeroClass = "Barbarian",
                            Name = "Shiva",
                            TownId = 7
                        },
                        new
                        {
                            Id = 101,
                            HeroClass = "Barbarian",
                            Name = "Gretchin",
                            TownId = 7
                        },
                        new
                        {
                            Id = 102,
                            HeroClass = "Barbarian",
                            Name = "Krellion",
                            TownId = 7
                        },
                        new
                        {
                            Id = 103,
                            HeroClass = "Barbarian",
                            Name = "Crag Hack",
                            TownId = 7
                        },
                        new
                        {
                            Id = 104,
                            HeroClass = "Barbarian",
                            Name = "Tyraxor",
                            TownId = 7
                        },
                        new
                        {
                            Id = 105,
                            HeroClass = "Battle Mage",
                            Name = "Gird",
                            TownId = 7
                        },
                        new
                        {
                            Id = 106,
                            HeroClass = "Battle Mage",
                            Name = "Vey",
                            TownId = 7
                        },
                        new
                        {
                            Id = 107,
                            HeroClass = "Battle Mage",
                            Name = "Dessa",
                            TownId = 7
                        },
                        new
                        {
                            Id = 108,
                            HeroClass = "Battle Mage",
                            Name = "Terek",
                            TownId = 7
                        },
                        new
                        {
                            Id = 109,
                            HeroClass = "Battle Mage",
                            Name = "Zubin",
                            TownId = 7
                        },
                        new
                        {
                            Id = 110,
                            HeroClass = "Battle Mage",
                            Name = "Gundula",
                            TownId = 7
                        },
                        new
                        {
                            Id = 111,
                            HeroClass = "Battle Mage",
                            Name = "Oris",
                            TownId = 7
                        },
                        new
                        {
                            Id = 112,
                            HeroClass = "Battle Mage",
                            Name = "Saurug",
                            TownId = 7
                        },
                        new
                        {
                            Id = 113,
                            HeroClass = "Beastmaster",
                            Name = "Bron",
                            TownId = 8
                        },
                        new
                        {
                            Id = 114,
                            HeroClass = "Beastmaster",
                            Name = "Drakon",
                            TownId = 8
                        },
                        new
                        {
                            Id = 115,
                            HeroClass = "Beastmaster",
                            Name = "Wystan",
                            TownId = 8
                        },
                        new
                        {
                            Id = 116,
                            HeroClass = "Beastmaster",
                            Name = "Tazar",
                            TownId = 8
                        },
                        new
                        {
                            Id = 117,
                            HeroClass = "Beastmaster",
                            Name = "Alkin",
                            TownId = 8
                        },
                        new
                        {
                            Id = 118,
                            HeroClass = "Beastmaster",
                            Name = "Korbac",
                            TownId = 8
                        },
                        new
                        {
                            Id = 119,
                            HeroClass = "Beastmaster",
                            Name = "Gerwulf",
                            TownId = 8
                        },
                        new
                        {
                            Id = 120,
                            HeroClass = "Beastmaster",
                            Name = "Broghild",
                            TownId = 8
                        },
                        new
                        {
                            Id = 121,
                            HeroClass = "Witch",
                            Name = "Mirlanda",
                            TownId = 8
                        },
                        new
                        {
                            Id = 122,
                            HeroClass = "Witch",
                            Name = "Rosic",
                            TownId = 8
                        },
                        new
                        {
                            Id = 123,
                            HeroClass = "Witch",
                            Name = "Voy",
                            TownId = 8
                        },
                        new
                        {
                            Id = 124,
                            HeroClass = "Witch",
                            Name = "Verdish",
                            TownId = 8
                        },
                        new
                        {
                            Id = 125,
                            HeroClass = "Witch",
                            Name = "Merist",
                            TownId = 8
                        },
                        new
                        {
                            Id = 126,
                            HeroClass = "Witch",
                            Name = "Styg",
                            TownId = 8
                        },
                        new
                        {
                            Id = 127,
                            HeroClass = "Witch",
                            Name = "Andra",
                            TownId = 8
                        },
                        new
                        {
                            Id = 128,
                            HeroClass = "Witch",
                            Name = "Tiva",
                            TownId = 8
                        },
                        new
                        {
                            Id = 129,
                            HeroClass = "Planeswalker",
                            Name = "Pasis",
                            TownId = 9
                        },
                        new
                        {
                            Id = 130,
                            HeroClass = "Planeswalker",
                            Name = "Thunar",
                            TownId = 9
                        },
                        new
                        {
                            Id = 131,
                            HeroClass = "Planeswalker",
                            Name = "Ignissa",
                            TownId = 9
                        },
                        new
                        {
                            Id = 132,
                            HeroClass = "Planeswalker",
                            Name = "Lacus",
                            TownId = 9
                        },
                        new
                        {
                            Id = 133,
                            HeroClass = "Planeswalker",
                            Name = "Monere",
                            TownId = 9
                        },
                        new
                        {
                            Id = 134,
                            HeroClass = "Planeswalker",
                            Name = "Erdamon",
                            TownId = 9
                        },
                        new
                        {
                            Id = 135,
                            HeroClass = "Planeswalker",
                            Name = "Fiur",
                            TownId = 9
                        },
                        new
                        {
                            Id = 136,
                            HeroClass = "Planeswalker",
                            Name = "Kalt",
                            TownId = 9
                        },
                        new
                        {
                            Id = 137,
                            HeroClass = "Elementalist",
                            Name = "Luna",
                            TownId = 9
                        },
                        new
                        {
                            Id = 138,
                            HeroClass = "Elementalist",
                            Name = "Brissa",
                            TownId = 9
                        },
                        new
                        {
                            Id = 139,
                            HeroClass = "Elementalist",
                            Name = "Ciele",
                            TownId = 9
                        },
                        new
                        {
                            Id = 140,
                            HeroClass = "Elementalist",
                            Name = "Labetha",
                            TownId = 9
                        },
                        new
                        {
                            Id = 141,
                            HeroClass = "Elementalist",
                            Name = "Inteus",
                            TownId = 9
                        },
                        new
                        {
                            Id = 142,
                            HeroClass = "Elementalist",
                            Name = "Aenain",
                            TownId = 9
                        },
                        new
                        {
                            Id = 143,
                            HeroClass = "Elementalist",
                            Name = "Gelare",
                            TownId = 9
                        },
                        new
                        {
                            Id = 144,
                            HeroClass = "Elementalist",
                            Name = "Grindan",
                            TownId = 9
                        },
                        new
                        {
                            Id = 145,
                            HeroClass = "Captain",
                            Name = "Corkes",
                            TownId = 10
                        },
                        new
                        {
                            Id = 146,
                            HeroClass = "Captain",
                            Name = "Jeremy",
                            TownId = 10
                        },
                        new
                        {
                            Id = 147,
                            HeroClass = "Captain",
                            Name = "Illor",
                            TownId = 10
                        },
                        new
                        {
                            Id = 148,
                            HeroClass = "Captain",
                            Name = "Derek",
                            TownId = 10
                        },
                        new
                        {
                            Id = 149,
                            HeroClass = "Captain",
                            Name = "Elmore",
                            TownId = 10
                        },
                        new
                        {
                            Id = 150,
                            HeroClass = "Captain",
                            Name = "Leena",
                            TownId = 10
                        },
                        new
                        {
                            Id = 151,
                            HeroClass = "Captain",
                            Name = "Anabel",
                            TownId = 10
                        },
                        new
                        {
                            Id = 152,
                            HeroClass = "Captain",
                            Name = "Cassiopeia",
                            TownId = 10
                        },
                        new
                        {
                            Id = 153,
                            HeroClass = "Captain",
                            Name = "Miriam",
                            TownId = 10
                        },
                        new
                        {
                            Id = 154,
                            HeroClass = "Captain",
                            Name = "Tark",
                            TownId = 10
                        },
                        new
                        {
                            Id = 155,
                            HeroClass = "Navigator",
                            Name = "Manfred",
                            TownId = 10
                        },
                        new
                        {
                            Id = 156,
                            HeroClass = "Navigator",
                            Name = "Zilare",
                            TownId = 10
                        },
                        new
                        {
                            Id = 157,
                            HeroClass = "Navigator",
                            Name = "Astra",
                            TownId = 10
                        },
                        new
                        {
                            Id = 158,
                            HeroClass = "Navigator",
                            Name = "Casmetra",
                            TownId = 10
                        },
                        new
                        {
                            Id = 159,
                            HeroClass = "Navigator",
                            Name = "Dargem",
                            TownId = 10
                        },
                        new
                        {
                            Id = 160,
                            HeroClass = "Navigator",
                            Name = "Andal",
                            TownId = 10
                        },
                        new
                        {
                            Id = 161,
                            HeroClass = "Navigator",
                            Name = "Eovacius",
                            TownId = 10
                        },
                        new
                        {
                            Id = 162,
                            HeroClass = "Navigator",
                            Name = "Spint",
                            TownId = 10
                        },
                        new
                        {
                            Id = 163,
                            HeroClass = "Mercenary",
                            Name = "Henrietta",
                            TownId = 11
                        },
                        new
                        {
                            Id = 164,
                            HeroClass = "Mercenary",
                            Name = "Sam",
                            TownId = 11
                        },
                        new
                        {
                            Id = 165,
                            HeroClass = "Mercenary",
                            Name = "Tancred",
                            TownId = 11
                        },
                        new
                        {
                            Id = 166,
                            HeroClass = "Mercenary",
                            Name = "Dury",
                            TownId = 11
                        },
                        new
                        {
                            Id = 167,
                            HeroClass = "Mercenary",
                            Name = "Morton",
                            TownId = 11
                        },
                        new
                        {
                            Id = 168,
                            HeroClass = "Mercenary",
                            Name = "Tavin",
                            TownId = 11
                        },
                        new
                        {
                            Id = 169,
                            HeroClass = "Mercenary",
                            Name = "Murdoch",
                            TownId = 11
                        },
                        new
                        {
                            Id = 170,
                            HeroClass = "Artificer",
                            Name = "Melchior",
                            TownId = 11
                        },
                        new
                        {
                            Id = 171,
                            HeroClass = "Artificer",
                            Name = "Floribert",
                            TownId = 11
                        },
                        new
                        {
                            Id = 172,
                            HeroClass = "Artificer",
                            Name = "Wynona",
                            TownId = 11
                        },
                        new
                        {
                            Id = 173,
                            HeroClass = "Artificer",
                            Name = "Todd",
                            TownId = 11
                        },
                        new
                        {
                            Id = 174,
                            HeroClass = "Artificer",
                            Name = "Agar",
                            TownId = 11
                        },
                        new
                        {
                            Id = 175,
                            HeroClass = "Artificer",
                            Name = "Bertram",
                            TownId = 11
                        },
                        new
                        {
                            Id = 176,
                            HeroClass = "Artificer",
                            Name = "Wrathmont",
                            TownId = 11
                        },
                        new
                        {
                            Id = 177,
                            HeroClass = "Artificer",
                            Name = "Ziph",
                            TownId = 11
                        },
                        new
                        {
                            Id = 178,
                            HeroClass = "Artificer",
                            Name = "Victoria",
                            TownId = 11
                        },
                        new
                        {
                            Id = 179,
                            HeroClass = "Artificer",
                            Name = "Eanswythe",
                            TownId = 11
                        },
                        new
                        {
                            Id = 180,
                            HeroClass = "Artificer",
                            Name = "Frederick",
                            TownId = 11
                        });
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OwnerId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.LeagueMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Glicko2Rating")
                        .HasColumnType("float");

                    b.Property<double>("Glicko2RatingDeviation")
                        .HasColumnType("float");

                    b.Property<double>("Glicko2Volatility")
                        .HasColumnType("float");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRatingUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlayerNickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "PlayerNickname")
                        .IsUnique();

                    b.ToTable("LeagueMemberships");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePosition")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("FavoriteHeroId")
                        .HasColumnType("int");

                    b.Property<int?>("FavoriteTownId")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("GamesWon")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TechnicalLosses")
                        .HasColumnType("int");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteHeroId");

                    b.HasIndex("FavoriteTownId");

                    b.HasIndex("LeagueMembershipId")
                        .IsUnique();

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.RatingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueMembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewRatingDeviation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewVolatility")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PreviousRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousRatingDeviation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousVolatility")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_RatingHistory_CalculatedAt");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_RatingHistory_GameId");

                    b.HasIndex("LeagueMembershipId")
                        .HasDatabaseName("IX_RatingHistory_LeagueMembershipId");

                    b.ToTable("RatingHistory", (string)null);
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The home of Knights and Clerics",
                            Name = "Castle"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The home of Rangers and Druids",
                            Name = "Rampart"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The home of Alchemists and Wizards",
                            Name = "Tower"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The home of Demoniac and Heretics",
                            Name = "Inferno"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The home of Death Knights and Necromancers",
                            Name = "Necropolis"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The home of Overlords and Warlocks",
                            Name = "Dungeon"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The home of Barbarians and Battle Mages",
                            Name = "Stronghold"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The home of Beastmasters and Witches",
                            Name = "Fortress"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The home of Planeswalkers and Elementalists",
                            Name = "Conflux"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The home of Captains and Navigators",
                            Name = "Cove"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The home of Artificiers and Mercenaries",
                            Name = "Factory"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreBurrow.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Game", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.League", "League")
                        .WithMany("Games")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreBurrow.Data.Entities.LeagueMembership", "Winner")
                        .WithMany("GamesWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("League");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.GameParticipant", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.Game", "Game")
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreBurrow.Data.Entities.Hero", "Hero")
                        .WithMany("GameParticipants")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreBurrow.Data.Entities.LeagueMembership", "LeagueMembership")
                        .WithMany("GameParticipants")
                        .HasForeignKey("LeagueMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreBurrow.Data.Entities.Town", "Town")
                        .WithMany("GameParticipants")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Hero");

                    b.Navigation("LeagueMembership");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Hero", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.Town", "Town")
                        .WithMany("Heroes")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.LeagueMembership", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.League", "League")
                        .WithMany("Memberships")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.PlayerStatistics", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.Hero", "FavoriteHero")
                        .WithMany("FavoriteInStatistics")
                        .HasForeignKey("FavoriteHeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScoreBurrow.Data.Entities.Town", "FavoriteTown")
                        .WithMany("FavoriteInStatistics")
                        .HasForeignKey("FavoriteTownId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScoreBurrow.Data.Entities.LeagueMembership", "LeagueMembership")
                        .WithOne("Statistics")
                        .HasForeignKey("ScoreBurrow.Data.Entities.PlayerStatistics", "LeagueMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteHero");

                    b.Navigation("FavoriteTown");

                    b.Navigation("LeagueMembership");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.RatingHistory", b =>
                {
                    b.HasOne("ScoreBurrow.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreBurrow.Data.Entities.LeagueMembership", "LeagueMembership")
                        .WithMany()
                        .HasForeignKey("LeagueMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("LeagueMembership");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Game", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Hero", b =>
                {
                    b.Navigation("FavoriteInStatistics");

                    b.Navigation("GameParticipants");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.League", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.LeagueMembership", b =>
                {
                    b.Navigation("GameParticipants");

                    b.Navigation("GamesWon");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("ScoreBurrow.Data.Entities.Town", b =>
                {
                    b.Navigation("FavoriteInStatistics");

                    b.Navigation("GameParticipants");

                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
